// Generated by CoffeeScript 1.4.0
var Knax, i;

i = require('inflection');

module.exports = Knax = {
  load: function(definition) {
    var directory, module;
    if (typeof definition.category !== 'undefined') {
      directory = i.pluralize(definition.category);
      console.log(directory);
      if (!definition["class"]) {
        throw 'local plugin requires category and class';
      }
      try {
        module = "./" + directory + "/" + definition["class"];
        return require(module);
      } catch (error) {
        if (error.code === 'MODULE_NOT_FOUND') {
          return Knax.loadNested(definition, error);
        }
        throw error;
      }
    }
  },
  loadNested: function(definition, error) {
    console.log('TODO: loadNested');
    throw error;
  }
};
